name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write
  
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Compress output
        run: cd out && zip -r ../out.zip .
      - name: Get latest tag
        id: tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "TAG_NAME=$LATEST_TAG" >> $GITHUB_OUTPUT
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: out.zip
          prerelease: false
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}